### ISSUE TITLE
crypto dependency

### ISSUE THREAD

**Issue by ameet123** [jamesmbourne/aws4-axios#377]
```
App •  ERROR  •  UI  in ./node_modules/aws4/aws4.js

Module not found: Can't resolve imported dependency "crypto"
Did you forget to install it? You can run: npm install --save crypto 
```
I am using *Quasar* and *Vue 3*
I have,
aws4-axios version : 2.4.3
aws4 that is installed has: 1.11.0

thanks.

**Comment by jamesmbourne** [comment]
Hey @ameet123 - this error comes from another package `aws4` rather than `aws4-axios` (this package).

You can see the import here: https://github.com/mhart/aws4/blob/master/aws4.js#L4

There are some related threads asking for browser support here:
https://github.com/mhart/aws4/issues/85
https://github.com/mhart/aws4/issues/62
